apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-mongo
  template:
    metadata:
      labels:
        app: fitness-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-mongo-service
spec:
  selector:
    app: fitness-mongo
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
