
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-mongo
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: fitness-mongo
  template:
    metadata:
      labels:
        app: fitness-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
        
        resources:

          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: fitness-data
          mountPath: /data/db
      volumes:
      -name: fitness-data
       emptyDir:
         sizeLimit: "512"
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-mongo-service
spec:
  selector:
    app: fitness-mongo
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
