apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-dynamic
provisioner: nfs.csi.k8s.io
parameters:
  server: 13.232.195.113
  share: /nfs-data
reclaimPolicy: Retain
volumeBindingMode: Immediate
