apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-config
data:
  MONGODB_URI: "mongodb://fitness-mongo-service:27017/fitness-tracker"
  PORT: "5000"
  HOST: "0.0.0.0"
  NODE_ENV: "production"

---




apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-app
spec:
  replicas: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: fitness-tracker-app
  template:
    metadata:
      labels:
        app: fitness-tracker-app
      annotations:
        ad.datadoghq.com/fitness-tracker-app.logs: >-
          [{"source":"nodejs","service":"fitness-tracker-service"},
           {"source":"nodejs","service":"fitness-tracker-app"}]
    spec:
      containers:
        - name: fitness-tracker-app
          image: pulkit197/fitness_tracker-master-copy3-fitness-app:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m" 
            requests:
              memory: "256Mi" 
              cpu: "100m"
          # ✔ All configMap vars removed
          # ✔ Direct env variables added
          envFrom:
          - configMapRef:
              name: fitness-config
      
---

apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
spec:
  selector:
    app: fitness-tracker-app
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
