apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-config
data:
  MONGODB_URI: "mongodb://fitness-mongo-service:27017/fitness-tracker"
  PORT: "5000"
  HOST: "0.0.0.0"
  NODE_ENV: "production"

---




apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fitness-tracker-app
  namespace: fitness-ns
spec:
  replicas: 3

  strategy:
    blueGreen:
      activeService: fitness-active
      previewService: fitness-preview
      autoPromotionEnabled: false

  selector:
    matchLabels:
      app: fitness-tracker-app
  template:
    metadata:
      labels:
        app: fitness-tracker-app
    spec:
      containers:
        - name: fitness-tracker-app
          image: team3kubectl/frontend:v1.1.1
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m" 
            requests:
              memory: "256Mi" 
              cpu: "100m"
          # ✔ All configMap vars removed
          # ✔ Direct env variables added
          envFrom:
          - configMapRef:
              name: fitness-config
      
