apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID printed by the 01-setup-identity.sh script
    azure.workload.identity/client-id: "493a7a1e-8032-4b8c-8ba4-62321355e7dd"
  labels:
    azure.workload.identity/use: "true"
